
gen Home_code =.
replace Home_code =1 if Home==" Arsenal"
replace Home_code =2 if Home==" Brighton and Hove Albion"
replace Home_code =3 if Home==" Bournemouth"
replace Home_code =4 if Home==" Burnley"
replace Home_code =5 if Home==" Chelsea"
replace Home_code =6 if Home==" Crystal Palace"
replace Home_code =7 if Home==" Everton"
replace Home_code =8 if Home==" Huddersfield Town"
replace Home_code =9 if Home==" Hull City"
replace Home_code =10 if Home==" Leicester City"
replace Home_code =11 if Home==" Liverpool"
replace Home_code =12 if Home==" Manchester City"
replace Home_code =13 if Home==" Middlesbrough"
replace Home_code =14 if Home==" Manchester United"
replace Home_code =15 if Home==" Newcastle United"
replace Home_code =16 if Home==" Southampton"
replace Home_code =17 if Home==" Stoke City"
replace Home_code =18 if Home==" Sunderland"
replace Home_code =19 if Home==" Swansea City"
replace Home_code =20 if Home==" Tottenham Hotspur"
replace Home_code =21 if Home==" Watford"
replace Home_code =22 if Home==" West Bromwich Albion"
replace Home_code =23 if Home==" West Ham United"


gen Away_code =.
replace Away_code =1 if Away=="Arsenal"
replace Away_code =2 if Away=="Brighton and Hove Albion"
replace Away_code =3 if Away=="Bournemouth"
replace Away_code =4 if Away=="Burnley"
replace Away_code =5 if Away=="Chelsea"
replace Away_code =6 if Away=="Crystal Palace"
replace Away_code =7 if Away=="Everton"
replace Away_code =8 if Away=="Huddersfield Town"
replace Away_code =9 if Away=="Hull City"
replace Away_code =10 if Away=="Leicester City"
replace Away_code =11 if Away=="Liverpool"
replace Away_code =12 if Away=="Manchester City"
replace Away_code =13 if Away=="Middlesbrough"
replace Away_code =14 if Away=="Manchester United"
replace Away_code =15 if Away=="Newcastle United"
replace Away_code =16 if Away=="Southampton"
replace Away_code =17 if Away=="Stoke City"
replace Away_code =18 if Away=="Sunderland"
replace Away_code =19 if Away=="Swansea City"
replace Away_code =20 if Away=="Tottenham Hotspur"
replace Away_code =21 if Away=="Watford"
replace Away_code =22 if Away=="West Bromwich Albion"
replace Away_code =23 if Away=="West Ham United"
