replace firstname = "Adam" if surname=="Adam Smith"
replace surname = "Smith" if surname=="Adam Smith"
replace firstname = "Andre" if surname=="Andre Ayew"
replace surname = "Ayew" if surname=="Andre Ayew"
replace firstname = "Badou" if surname=="Badou Ndiaye"
replace surname = "Ndiaye" if surname=="Badou Ndiaye"
replace firstname = "Bernardo" if surname=="Bernardo Silva"
replace surname = "Silva" if surname=="Bernardo Silva"
replace firstname = "Brad" if surname=="Brad Smith"
replace surname = "Smith" if surname=="Brad Smith"
replace firstname = "David" if surname=="David Luiz"
replace surname = "Luiz" if surname=="David Luiz"
replace firstname = "David" if surname=="David Silva"
replace surname = "Silva" if surname=="David Silva"
replace firstname = "Joao" if surname=="Joao Mario"
replace surname = "Mario" if surname=="Joao Mario"
replace firstname = "Joel" if surname=="Joel Pereira"
replace surname = "Pereira" if surname=="Joel Pereira"
replace firstname = "Jordan" if surname=="Jordan Ayew"
replace surname = "Ayew" if surname=="Jordan Ayew"
replace firstname="Jordan" if surname=="Jordan Ayew"
replace firstname="Ki" if surname=="Ki Sung-yueng"
replace firstname="Kiko" if surname=="Kiko Femenia"
replace firstname="Lee" if surname=="Lee Chung-yong"
replace firstname="Lewis" if surname=="Lewis Cook"
replace firstname="Lucas" if surname=="Lucas Moura"
replace firstname="Oriol" if surname=="Oriol Romeu"
replace firstname="Sheyi" if surname=="Sheyi Ojo"
replace firstname="Steve" if surname=="Steve Cook"
replace firstname="Yaya" if surname=="Yaya Toure"
replace surname="Ayew" if surname=="Yaya Toure"
replace surname="Sung-yueng" if surname=="Yaya Toure"
replace surname="Femenia" if surname=="Yaya Toure"
replace surname="Chung-yong" if surname=="Yaya Toure"
replace surname="Cook" if surname=="Yaya Toure"
replace surname="Moura" if surname=="Yaya Toure"
replace surname="Romeu" if surname=="Yaya Toure"
replace surname="Ojo" if surname=="Yaya Toure"
replace surname="Cook" if surname=="Yaya Toure"
replace surname="Toure" if surname=="Yaya Toure"

replace PlayerName = "Younes Kaboul" if PlayerName=="Younès Kaboul"
replace PlayerName = "Pierre-Emile Højbjerg" if PlayerName=="Pierre-Emile Höjbjerg"
replace PlayerName = "Alexander Sørloth" if PlayerName=="Alexander Sörloth"
