gen Home_code =.
replace Home_code =1 if Home==" Arsenal"
replace Home_code =2 if Home==" Brighton and Hove Albion"
replace Home_code =3 if Home==" Bournemouth"
replace Home_code =4 if Home==" Burnley"
replace Home_code =5 if Home==" Chelsea"
replace Home_code =6 if Home==" Crystal Palace"
replace Home_code =7 if Home==" Everton"
replace Home_code =8 if Home==" Huddersfield Town"
replace Home_code =9 if Home==" Hull City"
replace Home_code =10 if Home==" Leicester City"
replace Home_code =11 if Home==" Liverpool"
replace Home_code =12 if Home==" Manchester City"
replace Home_code =13 if Home==" Middlesbrough"
replace Home_code =14 if Home==" Manchester United"
replace Home_code =15 if Home==" Newcastle United"
replace Home_code =16 if Home==" Southampton"
replace Home_code =17 if Home==" Stoke City"
replace Home_code =18 if Home==" Sunderland"
replace Home_code =19 if Home==" Swansea City"
replace Home_code =20 if Home==" Tottenham Hotspur"
replace Home_code =21 if Home==" Watford"
replace Home_code =22 if Home==" West Bromwich Albion"
replace Home_code =23 if Home==" West Ham United"
